---
- name: Notify updates of CUDA via Slack
  when:
    - slack_token is defined
    - slack_channel is defined
    - slack_icon_url is defined
  environment:
    https_proxy: "{{ http_proxy if http_proxy is defined else '' }}"
  local_action:
    module: slack
    msg: 'The CUDA driver was updated.'
    token: "{{ slack_token }}"
    channel: "#{{ slack_channel }}"
    username: "{{ ansible_user }}@{{ inventory_hostname }}"
    icon_url: "{{ slack_icon_url }}"
