---
- name: Check NVIDIA driver
  when: nvidia_installer is defined
  shell: |
    nvidia-smi
  ignore_errors: true
  register: nvidia_smi
  changed_when: false

- name: Copy a NVIDIA installer
  when:
    - apt_nvidia_driver is not defined
    - nvidia_installer is defined
    - nvidia_smi is failed
  copy:
    src: "{{ nvidia_installer }}"
    dest: "/tmp/{{ nvidia_installer|basename }}"

- name: Install NVIDIA driver
  when:
    - apt_nvidia_driver is not defined
    - nvidia_installer is defined
    - nvidia_smi is failed
  become: true
  shell: |
    [[ $(lsmod | grep -c nvidia) -gt 0 ]] && rmmod nvidia_drm nvidia_modeset nvidia_uvm nvidia
    bash /tmp/{{ nvidia_installer|basename }} --dkms --silent
  notify: Notify updates of NVIDIA via Slack

- name: Install NVIDIA driver in Ubuntu
  when:
    - ansible_distribution == 'Ubuntu'
    - apt_nvidia_driver is defined
  become: true
  apt:
    autoclean: yes
    autoremove: yes
    update_cache: yes
    name: "{{ apt_nvidia_driver }}"
    state: latest
  notify: Notify updates of NVIDIA via Slack
