---
- name: Install nvidia-cuda-toolkit
  become: true
  apt:
    autoclean: yes
    autoremove: yes
    update_cache: yes
    name:
      - libnccl-dev
      - nsight-compute
      - nvidia-cuda-toolkit
      - nvidia-cudnn
    state: latest
