---
- name: Install the default NVIDIA CUDA SDK
  become: true
  ansible.builtin.apt:
    autoclean: yes
    autoremove: yes
    update_cache: yes
    name:
      - libnccl-dev
      - nvidia-cuda-toolkit
      - nvidia-cudnn
    state: latest

- name: Remove the outdated signing key
  become: true
  ansible.builtin.file:
    path: /etc/apt/trusted.gpg.d/7fa2af80.gpg
    state: absent

- name: Check if cuda-keyring is installed
  ansible.builtin.apt:
    name: cuda-keyring
    state: present
  ignore_errors: true
  register: cuda_keyring_is_present

- name: Download cuda-keyring
  when:
    - cuda_keyring_is_present is failed
  ansible.builtin.get_url:
    url: https://developer.download.nvidia.com/compute/cuda/repos/{{ ansible_distribution | lower }}{{ ansible_distribution_version | replace('.', '') }}/{{ ansible_architecture }}/cuda-keyring_1.1-1_all.deb
    dest: /tmp/cuda-keyring.deb
    mode: '0644'

- name: Install CUDA keyring
  when:
    - cuda_keyring_is_present is failed
  become: true
  ansible.builtin.apt:
    deb: /tmp/cuda-keyring.deb

- name: Clean up the temporary file
  ansible.builtin.file:
    path: /tmp/cuda-keyring.deb
    state: absent

- name: Install the latest NVIDIA CUDA SDK
  become: true
  ansible.builtin.apt:
    autoclean: yes
    autoremove: yes
    update_cache: yes
    name:
      - cuda-toolkit
      - cudnn
      - nvidia-gds
    state: latest

- name: Set environment variables for CUDA
  become: true
  ansible.builtin.copy:
    dest: /etc/profile.d/cuda.sh
    content: |
      export CUDA_HOME="/usr/local/cuda"
      export PATH="${CUDA_HOME}/bin:${PATH}"
      export LD_LIBRARY_PATH="${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}"
    mode: '0644'
